export enum TypeAliment {
  ALCOOL = 'alcool',
  BASE = 'base',
  CEREALE = 'cereale',
  CHAMPIGNON = 'champignon',
  FROMAGE = 'fromage',
  FRUIT = 'fruit',
  FRUIT_A_COQUE = 'fruit a coque',
  FRUIT_DE_MER = 'fruit de mer',
  HERBE = 'herbe',
  EPICE = 'epice',
  CHARCUTERIE = 'charcuterie',
  LAITIER = 'laitier',
  LEGUME = 'legume',
  LIQUIDE = 'liquide',
  POISSON = 'poisson',
  SALADE = 'salade',
  SAUCE = 'sauce',
  SOFT = 'soft',
  SUCRE = 'sucre',
  VIANDE_BLANCHE = 'viande blanche',
  VIANDE_ROUGE = 'viande rouge'
}
