import type { Metadata } from 'next';
import {
  Montserrat,
} from 'next/font/google';
import { Toaster } from '@/ui/sonner';
import { cn } from '@/lib/utils';
import backgroundImage from '@/public/background.avif';


export const dynamic = 'force-dynamic';
const montserrat = Montserrat({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
      <main
        style={{ backgroundImage: `url(${backgroundImage.src})` }}
        className={cn(
          montserrat.className,
          'w-screen h-screen relative bg-bottom bg-cover bg-no-repeat overflow-y-auto',
        )}
      >
        {children}
      </main>
      <Toaster />
    </>
  );
}
