import fs from 'node:fs';
import path from 'node:path';
import adjectifs from '../data/menu-adjectif';
import complements from '../data/menu-complement';
import ingredients from '../data/menu-ingredient';
import liens from '../data/menu-lien';
import plats from '../data/menu-plat';
import posts from '../data/menu-post';
import preSauces from '../data/menu-pre-sauce';
import pres from '../data/menu-pre';
import sauceTypes from '../data/menu-sauce-type';
import titles from '../data/menu-title';
import { TypeAliment } from '@/types/enums/type-aliment';
import { TypePlat } from '@/types/enums/type-plat';

function buildIndex<TItem, TType extends string>(
  items: readonly TItem[],
  types: readonly TType[],
  getTypes: (item: TItem) => readonly TType[] | null,
): Record<TType, number[]> {
  return Object.fromEntries(
    types.map((type) => [
      type,
      items
        .map((item, index) => getTypes(item)?.includes(type) ? index : -1)
        .filter((index) => index !== -1),
    ]),
  ) as Record<TType, number[]>;
}

function formatIndexedArray(sourceName: string, indexes: readonly number[]): string {
  if (indexes.length === 0) {
    return '[]';
  }

  return `[${indexes.map((index) => `${sourceName}[${index}]`).join(', ')}]`;
}

function formatIndex<TType extends string>(
  sourceName: string,
  enumName: string,
  enumEntries: readonly [string, TType][],
  index: Record<TType, number[]>,
): string {
  return `{\n${enumEntries
    .map(([key, value]) => `    [${enumName}.${key}]: ${formatIndexedArray(sourceName, index[value])},`)
    .join('\n')}\n  }`;
}

function formatData(name: string, typeName: string, value: unknown): string {
  return `const ${name} = ${JSON.stringify(value, null, 2)} as unknown as ${typeName};`;
}

const typeAlimentEntries = Object.entries(TypeAliment) as [string, TypeAliment][];
const typePlatEntries = Object.entries(TypePlat) as [string, TypePlat][];

const ingredientsByType = buildIndex(ingredients, Object.values(TypeAliment), (item) => item.types);
const adjectifsByType = buildIndex(adjectifs, Object.values(TypeAliment), (item) => item.types);
const liensByType = buildIndex(liens, Object.values(TypeAliment), (item) => item.compatibleIngredientTypes);
const platsByType = buildIndex(plats, Object.values(TypePlat), (item) => item.types);
const postsByType = buildIndex(posts, Object.values(TypePlat), (item) => item.types);
const presByType = buildIndex(pres, Object.values(TypePlat), (item) => item.types);
const sauceTypesByType = buildIndex(sauceTypes, Object.values(TypePlat), (item) => item.types);

const generated = `/* This file is generated by scripts/generate-menu-data.ts. Do not edit manually. */
import { TypeAliment } from '@/types/enums/type-aliment';
import { TypePlat } from '@/types/enums/type-plat';
import type { Adjectif } from '@/types/data/adjectif';
import type { Complement } from '@/types/data/complement';
import type { Ingredient } from '@/types/data/ingredient';
import type { Lien } from '@/types/data/lien';
import type { Plat } from '@/types/data/plat';
import type { Post } from '@/types/data/post';
import type { PreSauce } from '@/types/data/pre-sauce';
import type { Pre } from '@/types/data/pre';
import type { SauceType } from '@/types/data/sauce-type';
import type { Title } from '@/types/data/title';
import type { Menu } from '@/types/menu';
import type { MenuIndexes } from '@/types/menu-indexes';

${formatData('adjectifs', 'Adjectif[]', adjectifs)}

${formatData('complements', 'Complement[]', complements)}

${formatData('ingredients', 'Ingredient[]', ingredients)}

${formatData('liens', 'Lien[]', liens)}

${formatData('plats', 'Plat[]', plats)}

${formatData('posts', 'Post[]', posts)}

${formatData('preSauces', 'PreSauce[]', preSauces)}

${formatData('pres', 'Pre[]', pres)}

${formatData('sauceTypes', 'SauceType[]', sauceTypes)}

${formatData('titles', 'Title[]', titles)}

export const indexes: MenuIndexes = {
  adjectifs,
  liens,
  ingredientsByType: ${formatIndex('ingredients', 'TypeAliment', typeAlimentEntries, ingredientsByType)},
  adjectifsByType: ${formatIndex('adjectifs', 'TypeAliment', typeAlimentEntries, adjectifsByType)},
  liensByType: ${formatIndex('liens', 'TypeAliment', typeAlimentEntries, liensByType)},
  platsByType: ${formatIndex('plats', 'TypePlat', typePlatEntries, platsByType)},
  postsByType: ${formatIndex('posts', 'TypePlat', typePlatEntries, postsByType)},
  presByType: ${formatIndex('pres', 'TypePlat', typePlatEntries, presByType)},
  sauceTypesByType: ${formatIndex('sauceTypes', 'TypePlat', typePlatEntries, sauceTypesByType)},
};

const menuData: Menu = {
  complements,
  titles,
  preSauces,
  indexes,
};

export default menuData;
`;

const outputDir = path.join(process.cwd(), 'data-build');
fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(path.join(outputDir, 'menu-data.generated.ts'), generated);

console.log('Generated data-build/menu-data.generated.ts');
