import { TypeAliment } from '@/types/enums/type-aliment';

export const alimentTypePresets = {
  all: [
    TypeAliment.ALCOOL,
    TypeAliment.BASE,
    TypeAliment.CEREALE,
    TypeAliment.CHAMPIGNON,
    TypeAliment.FROMAGE,
    TypeAliment.FRUIT,
    TypeAliment.FRUIT_A_COQUE,
    TypeAliment.FRUIT_DE_MER,
    TypeAliment.HERBE,
    TypeAliment.EPICE,
    TypeAliment.CHARCUTERIE,
    TypeAliment.LAITIER,
    TypeAliment.LEGUME,
    TypeAliment.LIQUIDE,
    TypeAliment.POISSON,
    TypeAliment.SALADE,
    TypeAliment.SAUCE,
    TypeAliment.SOFT,
    TypeAliment.SUCRE,
    TypeAliment.VIANDE_BLANCHE,
    TypeAliment.VIANDE_ROUGE,
  ],
  allWithoutCharcuterieAndRedMeat: [
    TypeAliment.ALCOOL,
    TypeAliment.BASE,
    TypeAliment.CEREALE,
    TypeAliment.CHAMPIGNON,
    TypeAliment.FROMAGE,
    TypeAliment.FRUIT,
    TypeAliment.FRUIT_A_COQUE,
    TypeAliment.FRUIT_DE_MER,
    TypeAliment.HERBE,
    TypeAliment.EPICE,
    TypeAliment.LAITIER,
    TypeAliment.LEGUME,
    TypeAliment.LIQUIDE,
    TypeAliment.POISSON,
    TypeAliment.SALADE,
    TypeAliment.SAUCE,
    TypeAliment.SOFT,
    TypeAliment.SUCRE,
  ],
  fruit: [TypeAliment.FRUIT],
  vegetable: [TypeAliment.LEGUME],
  seafood: [TypeAliment.FRUIT_DE_MER],
  fish: [TypeAliment.POISSON],
  charcuterie: [TypeAliment.CHARCUTERIE],
  sugar: [TypeAliment.SUCRE],
  base: [TypeAliment.BASE],
  mushroom: [TypeAliment.CHAMPIGNON],
  cheese: [TypeAliment.FROMAGE],
  cereal: [TypeAliment.CEREALE],
  nut: [TypeAliment.FRUIT_A_COQUE],
  salad: [TypeAliment.SALADE],
  whiteMeat: [TypeAliment.VIANDE_BLANCHE],
  redMeat: [TypeAliment.VIANDE_ROUGE],
  herbSauce: [TypeAliment.HERBE, TypeAliment.SAUCE],
  fruitSauce: [TypeAliment.FRUIT, TypeAliment.SAUCE],
  alcoholSauce: [TypeAliment.ALCOOL, TypeAliment.SAUCE],
  cheeseSauce: [TypeAliment.FROMAGE, TypeAliment.SAUCE],
  spiceSauce: [TypeAliment.EPICE, TypeAliment.SAUCE],
  redMeatSauce: [TypeAliment.VIANDE_ROUGE, TypeAliment.SAUCE],
  baseCereal: [TypeAliment.BASE, TypeAliment.CEREALE],
  liquidSauce: [TypeAliment.LIQUIDE, TypeAliment.SAUCE],
  mushroomSauce: [TypeAliment.CHAMPIGNON, TypeAliment.SAUCE],
  vegetableSauce: [TypeAliment.LEGUME, TypeAliment.SAUCE],
  sugarSauce: [TypeAliment.SUCRE, TypeAliment.SAUCE],
  whiteMeatSauce: [TypeAliment.VIANDE_BLANCHE, TypeAliment.SAUCE],
  spiceSauceSugar: [TypeAliment.EPICE, TypeAliment.SAUCE, TypeAliment.SUCRE],
  fruitSaladSauce: [TypeAliment.FRUIT, TypeAliment.SALADE, TypeAliment.SAUCE],
  vegetableSalad: [TypeAliment.LEGUME, TypeAliment.SALADE],
  fishSauce: [TypeAliment.POISSON, TypeAliment.SAUCE],
  alcoholLiquidSauce: [TypeAliment.ALCOOL, TypeAliment.LIQUIDE, TypeAliment.SAUCE],
  nutSauce: [TypeAliment.FRUIT_A_COQUE, TypeAliment.SAUCE],
  seafoodSauce: [TypeAliment.FRUIT_DE_MER, TypeAliment.SAUCE],
  none: [],
  redAndWhiteMeat: [TypeAliment.VIANDE_ROUGE, TypeAliment.VIANDE_BLANCHE],
  fishAndSeafood: [TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER],
  fruitAndNut: [TypeAliment.FRUIT, TypeAliment.FRUIT_A_COQUE],
  fruitSugarNut: [TypeAliment.FRUIT, TypeAliment.SUCRE, TypeAliment.FRUIT_A_COQUE],
  fruitNutSugar: [TypeAliment.FRUIT, TypeAliment.FRUIT_A_COQUE, TypeAliment.SUCRE],
  fruitNutSugarCereal: [TypeAliment.FRUIT, TypeAliment.FRUIT_A_COQUE, TypeAliment.SUCRE, TypeAliment.CEREALE],
  fruitNutSugarCheese: [TypeAliment.FRUIT, TypeAliment.FRUIT_A_COQUE, TypeAliment.SUCRE, TypeAliment.FROMAGE],
  fruitSugarNutCheese: [TypeAliment.FRUIT, TypeAliment.SUCRE, TypeAliment.FRUIT_A_COQUE, TypeAliment.FROMAGE],
  savoryCore: [TypeAliment.LEGUME, TypeAliment.VIANDE_ROUGE, TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER, TypeAliment.CHAMPIGNON, TypeAliment.VIANDE_BLANCHE],
  savoryCoreWithCheese: [TypeAliment.LEGUME, TypeAliment.VIANDE_ROUGE, TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER, TypeAliment.CHAMPIGNON, TypeAliment.VIANDE_BLANCHE, TypeAliment.FROMAGE],
  friedSavoryCore: [TypeAliment.VIANDE_BLANCHE, TypeAliment.VIANDE_ROUGE, TypeAliment.FROMAGE, TypeAliment.LEGUME, TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER, TypeAliment.CHAMPIGNON],
  savoryCoreWithCheeseBeforeWhiteMeat: [TypeAliment.LEGUME, TypeAliment.VIANDE_ROUGE, TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER, TypeAliment.CHAMPIGNON, TypeAliment.FROMAGE, TypeAliment.VIANDE_BLANCHE],
  fullSavoryComposition: [TypeAliment.LEGUME, TypeAliment.VIANDE_ROUGE, TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER, TypeAliment.CHAMPIGNON, TypeAliment.SALADE, TypeAliment.FROMAGE, TypeAliment.CEREALE, TypeAliment.VIANDE_BLANCHE, TypeAliment.CHARCUTERIE],
  savoryCoreWithSaladAndWhiteMeat: [TypeAliment.LEGUME, TypeAliment.VIANDE_ROUGE, TypeAliment.POISSON, TypeAliment.FRUIT_DE_MER, TypeAliment.CHAMPIGNON, TypeAliment.SALADE, TypeAliment.VIANDE_BLANCHE],
} satisfies Record<string, TypeAliment[]>;
